project:
  type: book
  output-dir: docs
  
book:
  title: "Hands-On Programming with R"
  author: "Garrett Grolemund"
  description: | 
    This book will teach you how to program in R, with hands-on examples. I 
    wrote it for non-programmers to provide a friendly introduction to the R
    language. You'll learn how to load data, assemble and disassemble data 
    objects, navigate R's environment system, write your own functions, and
    use all of R's programming tools. Throughout the book, you'll use your
    newfound skills to solve practical data science problems.
  site-url: https://rstudio-education.github.io/hopr/
  repo-url: https://github.com/jjallaire/hopr/
  repo-branch: master
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.Rmd
    - preface.Rmd
    - part: dice.Rmd
      chapters: 
        - basics.Rmd
        - packages.Rmd
    - part: cards.Rmd
      chapters:
        - objects.Rmd
        - notation.Rmd
        - modifying.Rmd
        - environments.Rmd
    - part: slots.Rmd
      chapters:
        - programs.Rmd
        - s3.Rmd
        - loops.Rmd
        - speed.Rmd
  appendices:
    - a1-starting.Rmd
    - a2-packages.Rmd
    - a3-updating.Rmd
    - a4-data.Rmd
    - a5-debug.Rmd 

format:
  html: 
    theme: cosmo
    code-link: false
  pdf: default
  epub: default
