project:
  type: book
  
book:
  title: "Hands-On Programming with R"
  author: "Garrett Grolemund"
  description: | 
    This book will teach you how to program in R, with hands-on examples. I 
    wrote it for non-programmers to provide a friendly introduction to the R
    language. You'll learn how to load data, assemble and disassemble data 
    objects, navigate R's environment system, write your own functions, and
    use all of R's programming tools. Throughout the book, you'll use your
    newfound skills to solve practical data science problems.
  site-url: https://rstudio-education.github.io/hopr/
  repo-url: https://github.com/rstudio-education/hopr
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  downloads: [pdf, epub]
  contents:
    - index.rmd
    - preface.rmd
    - part: "Part 1"
      contents: 
        - dice.rmd
        - basics.rmd
        - packages.rmd
    - part: "Part 2"
      contents:
        - cards.rmd
        - objects.rmd
        - notation.rmd
        - modifying.rmd
        - environments.rmd
    - part: "Part 3"
      contents:
        - slots.rmd
        - programs.rmd
        - s3.rmd
        - loops.rmd
        - speed.rmd
  appendix:
    - a1-starting.rmd
    - a2-packages.rmd
    - a3-updating.rmd
    - a4-data.rmd
    - a5-debug.rmd 
    
freeze: auto
    
format:
  html: 
    theme: cosmo
  pdf: default
  epub: default
