project:
  type: book
  output-dir: docs
  resources: [.nojekyll]
  
book:
  title: "Hands-On Programming with R"
  author: "Garrett Grolemund"
  description: | 
    This book will teach you how to program in R, with hands-on examples. I 
    wrote it for non-programmers to provide a friendly introduction to the R
    language. You'll learn how to load data, assemble and disassemble data 
    objects, navigate R's environment system, write your own functions, and
    use all of R's programming tools. Throughout the book, you'll use your
    newfound skills to solve practical data science problems.
  site-url: https://rstudio-education.github.io/hopr/
  repo-url: https://github.com/jjallaire/hopr/
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.md
    - preface.md
    - part: "Part 1"
      chapters: 
        - dice.md
        - basics.md
        - packages.md
    - part: "Part 2"
      chapters:
        - cards.md
        - objects.md
        - notation.md
        - modifying.md
        - environments.md
    - part: "Part 3"
      chapters:
        - slots.md
        - programs.md
        - s3.md
        - loops.md
        - speed.md
  appendices:
    - a1-starting.md
    - a2-packages.md
    - a3-updating.md
    - a4-data.md
    - a5-debug.md 

format:
  html: 
    theme: cosmo
  pdf: default
  epub: default
